services:
  api:
    build:
      context: .
      dockerfile: WIFIService.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ExternalServices__NetworkInfrastructureApi__BaseUrl=http://wiremock:9001/
      - ExternalServices__NetworkControllerApi__BaseUrl=http://wiremock:9002/
    depends_on:
      - wiremock

  wiremock:
    build:
      context: .
      dockerfile: WIFIService.WireMock/Dockerfile
    ports:
      - "9001:9001"
      - "9002:9002"
